---
- name: Gather EC2 instance metadata
  ec2_metadata_facts:

- name: Undeploy application on {{ansible_hostname}}
  command: wget "http://{{tomcat_user}}:{{tomcat_pwd}}@{{ansible_ec2_public_ipv4}}:8080/manager/text/undeploy?path=/helloworld" -O - -q
