---
- name: Deploy the new WAR file to target servers
  
  copy:
    src: "{{ item }}"
    dest: /opt/tomcat/latest/webapps/
    owner: tomcat
    group: tomcat
    mode: '0664'
  with_fileglob: "target/*.war"
